---
version: "3.8"

services:
  splunk:
    image: splunk/splunk:latest
    restart: always
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=HelloWorld123
      - SPLUNK_APPS_URL=https://github.com/yaleman/TA-pushover/releases/download/latest/TA-pushover.tgz
    ports:
      - "8000:8000"
      - "18089:8089"
    volumes:
      - "splunk:/opt"


volumes:
  splunk: